# Generated by Django 4.0.3 on 2022-03-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiyatroapp', '0002_images_alter_tiyatro_video_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
