# Generated by Django 4.0.3 on 2022-03-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiyatroapp', '0003_rename_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Adres')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Telefon Numarası')),
                ('facebook_url', models.CharField(max_length=250, verbose_name='Facebook Adresi')),
                ('twitter_url', models.CharField(max_length=250, verbose_name='Twitter Adresi')),
                ('youtube_url', models.CharField(max_length=250, verbose_name='Youtube Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
        migrations.AddField(
            model_name='tiyatro',
            name='theater_date',
            field=models.DateTimeField(null=True, verbose_name='Tembihname Tarihi'),
        ),
    ]
