# Generated by Django 4.0.3 on 2022-03-08 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiyatroapp', '0005_about_homepage_remove_contact_twitter_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Sayi')),
                ('label', models.CharField(max_length=250, verbose_name='Etiket')),
                ('status', models.CharField(choices=[('publish', 'Yayınlandı'), ('deleted', 'Silindi')], default='publish', max_length=25, verbose_name='Statü')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tiyatroapp.card', verbose_name='Kartlar'),
        ),
    ]
