# Generated by Django 4.0.3 on 2022-03-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiyatroapp', '0006_card_about_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='card',
            new_name='cards',
        ),
    ]
