# Generated by Django 4.0.3 on 2022-03-08 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiyatroapp', '0007_rename_card_about_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiyatroapp.about', verbose_name='Hakkımızda'),
        ),
    ]
