# Generated by Django 4.0.3 on 2022-03-08 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiyatroapp', '0008_remove_about_cards_card_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tiyatroapp.about'),
        ),
    ]
