# Generated by Django 4.0.3 on 2022-03-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiyatroapp', '0009_alter_card_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'Hakkımızda'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name_plural': 'Kartlar'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'İletişim'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Anasayfa'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Fotoğraflar'},
        ),
        migrations.AlterModelOptions(
            name='tiyatro',
            options={'verbose_name_plural': 'Tiyatrolar'},
        ),
    ]
